---
title: "results_maps"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages
```{r}
library(tidyverse)
library(sf)
library(tmap)
library(tmaptools)
library(here)
library(janitor) 
library(ggthemes)
library(ggmap)
```

Hotspot maps
```{r}
tmap_mode('plot')

#Dry results
subcatch_dry <- read_sf(dsn = here("wailupe_subcatch_outlines"), layer = "subcatch_areaupdate") %>%
  st_transform(crs = 4326) %>% 
  clean_names() %>% 
  select(subcatchment = objectid_1) %>% 
  merge(results_dry) %>% 
  filter(subcatchment != "5")


#  Total volume hotspots  
hotspots_dry_total <- tm_basemap("OpenStreetMap.Mapnik") +
  tm_shape(subcatch_dry, unit = "Miles") +
  tm_polygons("runoff_coeff", alpha = 0.8, palette = "Blues", style = "cont", n=8, title = "Runoff Coefficient") +
  tm_layout(title = "December 2010 storm", inner.margins=c(.05, .05, 0.1, .53), legend.position =  c(.6,.63), legend.title.size = 1.4, legend.text.size = 1) +
  tm_text("subcatchment", size = 0.3) +
  tm_scale_bar(position = c(.6,.58), breaks = c(0, 0.2, 0.4, 0.6, 0.8,1)) +
  tm_compass(position = c(.58,.51))
tmap_save(hotspots_dry_total, "hotspots_dry_total.png")

#  Peak flow hotspots
hotspots_dry_peak <- tm_basemap("OpenStreetMap.Mapnik") +
  tm_shape(subcatch_dry, unit = "Miles") +
  tm_polygons("peak_runoff_cfs", alpha = 0.75, palette = "Greens", style = "cont", n=8, legend.hist = TRUE, title = "Peak Discharge (cfs)") +
  tm_layout(title = "December 2010 storm", inner.margins=c(.05, .05, 0.1, .53), legend.position =  c(.6,.35), legend.title.size = 1.4, legend.text.size = 1) +
  tm_text("subcatchment", size = 0.3) +
  tm_scale_bar(position = c(.6,.61), breaks = c(0, 0.2, 0.4, 0.6, 0.8,1)) +
  tm_compass(position = c(.58,.54))
tmap_save(hotspots_dry_peak, "hotspots_dry_peak.png")

#Wet results
subcatch_wet <- read_sf(dsn = here("wailupe_subcatch_outlines"), layer = "subcatch_areaupdate") %>%
  st_transform(crs = 4326) %>% 
  clean_names() %>% 
  select(subcatchment = objectid_1) %>% 
  merge(results_wet) %>% 
   filter(subcatchment != "5")

#  Total volume hotspots  
hotspots_wet_total <- tm_basemap("OpenStreetMap.Mapnik") +
  tm_shape(subcatch_wet, unit = "Miles") +
  tm_polygons("runoff_coeff", alpha = 0.8, palette = "Blues", style = "cont", n=8, legend.hist = TRUE, title = "Runoff Coefficient") +
  tm_layout(title = "March 2009 storm", inner.margins=c(.05, .05, 0.1, .53), legend.position =  c(.6,.32), legend.title.size = 1.4, legend.text.size = 1) +
  tm_text("subcatchment", size = 0.3) +
  tm_scale_bar(position = c(.6,.59), breaks = c(0, 0.2, 0.4, 0.6, 0.8,1)) +
  tm_compass(position = c(.58,.52))
tmap_save(hotspots_wet_total, "hotspots_wet_total.png")


#  Peak flow hotspots
hotspots_wet_peak <- tm_basemap("OpenStreetMap.Mapnik") +
  tm_shape(subcatch_wet, unit = "Miles") +
  tm_polygons("peak_runoff_cfs", alpha = 0.75, palette = "Greens", style = "cont", n=8, legend.hist = TRUE, title = "Peak Discharge (cfs)") +
  tm_layout(title = "March 2009 storm", inner.margins=c(.05, .05, 0.1, .53), legend.position =  c(.6,.27), legend.title.size = 1.4, legend.text.size = 1) +
  tm_text("subcatchment", size = 0.3) +
  tm_scale_bar(position = c(.6,.54), breaks = c(0, 0.2, 0.4, 0.6, 0.8,1)) +
  tm_compass(position = c(.58,.47))
tmap_save(hotspots_wet_peak, "hotspots_wet_peak.png")


#Top 20 of total volume
top20_dry_total <- subcatch_dry %>% 
  arrange(-runoff_coeff) %>% 
  head(20)

top20_wet_total <- subcatch_wet %>% 
  arrange(-runoff_coeff) %>% 
  head(20)

common_total_vector <- as.data.frame(intersect(top20_dry_total$subcatchment, top20_wet_total$subcatchment)) 
colnames(common_total_vector) <- c("subcatchment")


common_total <- subcatch_dry %>% 
  mutate(hotspot = case_when(
  subcatchment == "21" | 
  subcatchment == "22" |
  subcatchment == "23" |
  subcatchment == "29" | 
  subcatchment == "40" | 
  subcatchment == "45" |
  subcatchment == "46" |
  subcatchment == "47" | 
  subcatchment == "49" | 
  subcatchment == "51" |
  subcatchment == "54" | 
  subcatchment == "59" | 
  subcatchment == "60" | 
  subcatchment == "63" | 
  subcatchment == "65" | 
  subcatchment == "67" | 
  subcatchment == "68" | 
  subcatchment == "71" | 
  subcatchment == "89" ~ "Hotspot"))

common_total$hotspot <- as.factor(common_total$hotspot)

top20_total_map <- tm_basemap("Hydda.Base") +
  tm_shape(common_total, unit = "Miles") +
  tm_polygons("hotspot", title = "Legend", textNA = "Subcatchment", palette="#045a8d", alpha = 0.8)+
  tm_layout(inner.margins=c(.05, .05, .05, .52), legend.position =  c(.56,.8),legend.title.size = 1.4, legend.text.size = 1) +
  tm_text("subcatchment", size = 0.3) +
  tm_scale_bar(position = c(.56,.75), breaks = c(0, 0.2, 0.4, 0.6, 0.8,1)) +
  tm_compass(position = c(.54,.68))

tmap_save(top20_total_map, "top20_total_map.png")

#Top 20 of peak volume

top20_dry_peak <- subcatch_dry %>% 
  arrange(-peak_runoff_cfs) %>% 
  head(20)

top20_wet_peak <- subcatch_wet %>% 
  arrange(-peak_runoff_cfs) %>% 
  head(20)

common_peak_vector <- as.data.frame(intersect(top20_dry_peak$subcatchment, top20_wet_peak$subcatchment)) 
colnames(common_peak_vector) <- c("subcatchment")

common_peak <- subcatch_dry %>% 
  mutate(hotspot = case_when(
  subcatchment == "1" | 
  subcatchment == "2" |
  subcatchment == "3" |
  subcatchment == "7" | 
  subcatchment == "11" | 
  subcatchment == "23" |
  subcatchment == "28" |
  subcatchment == "38" | 
  subcatchment == "42" | 
  subcatchment == "58" |
  subcatchment == "62" | 
  subcatchment == "63" | 
  subcatchment == "74" | 
  subcatchment == "75" | 
  subcatchment == "76" | 
  subcatchment == "78" | 
  subcatchment == "79" | 
  subcatchment == "89" | 
  subcatchment == "94" ~ "Hotspot"))

common_peak$hotspot <- as.factor(common_peak$hotspot)

top20_peak_map <- tm_basemap("Hydda.Base") +
  tm_shape(common_peak, unit = "Miles") +
  tm_polygons("hotspot", title = "Legend", textNA = "Subcatchment", palette="#006d2c", alpha = 0.8)+
  tm_layout(inner.margins=c(.05, .05, .05, .52), legend.position =  c(.56,.8),legend.title.size = 1.4, legend.text.size = 1) +
  tm_text("subcatchment", size = 0.3) +
  tm_scale_bar(position = c(.56,.75), breaks = c(0, 0.2, 0.4, 0.6, 0.8,1)) +
  tm_compass(position = c(.54,.68))

tmap_save(top20_peak_map, "top20_peak_map.png")

```

Satellite maps
```{r}

ph_basemap <- get_map(location= c(lon = -157.755877, lat = 21.292075), zoom=14, maptype = 'terrain')
ggmap(ph_basemap) +
    geom_sf(data = philly_crimes_sf, aes(fill=homic_rate_cat), inherit.aes = FALSE) +
    scale_fill_brewer(palette = "OrRd") +
  +
    coord_sf(crs = st_crs(4326))

maunalua_basemap <- get_googlemap(center = c(lon = -157.755877, lat = 21.292075),
  zoom = 12, maptype = "satellite") 
  
  ggmap(maunalua_basemap)



satellite_peak <- ggplot(data = common_peak) +
  geom_sf(aes(fill = subcatchment),color = NA) + 
  scale_fill_paletteer_c("viridis::viridis") +
  theme_minimal()
satellite_peak

# Let's crop it: 
world_base +
  coord_sf(xlim = c(-20, 50), ylim = c(-40, 40), expand = FALSE)



```

Satellite maps google earth
```{r}
#Keep the common hotspots only
common_peak_only <- subcatch_dry %>% 
  filter(
  subcatchment == "1" | 
  subcatchment == "2" |
  subcatchment == "3" |
  subcatchment == "7" | 
  subcatchment == "11" | 
  subcatchment == "23" |
  subcatchment == "28" |
  subcatchment == "38" | 
  subcatchment == "42" | 
  subcatchment == "58" |
  subcatchment == "62" | 
  subcatchment == "63" | 
  subcatchment == "74" | 
  subcatchment == "75" | 
  subcatchment == "76" | 
  subcatchment == "78" | 
  subcatchment == "79" | 
  subcatchment == "89" | 
  subcatchment == "94" )

#Export as .shp
st_write(common_peak_only, "common_peak.shp")


#Keep the common hotspots only
common_total_only <- subcatch_dry %>% 
  filter(
  subcatchment == "21" | 
  subcatchment == "22" |
  subcatchment == "23" |
  subcatchment == "29" | 
  subcatchment == "40" | 
  subcatchment == "45" |
  subcatchment == "46" |
  subcatchment == "47" | 
  subcatchment == "49" | 
  subcatchment == "51" |
  subcatchment == "54" | 
  subcatchment == "59" | 
  subcatchment == "60" | 
  subcatchment == "63" | 
  subcatchment == "65" | 
  subcatchment == "67" | 
  subcatchment == "68" | 
  subcatchment == "71" | 
  subcatchment == "89")

#Export as .shp
st_write(common_total_only, "common_total.shp")
```

