---
title: "results_graphs"
author: "Eleonore Durand"
date: "February 13, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


```{r, fig.width=10, fig.height=5, results= 'asis'}

#dryresults

subcatch<- read_csv("subcatchments_all.csv") %>% 
  mutate(subcatchment= OBJECTID_1) %>% 
  select(subcatchment, Curve_Number, Slope, percent_imp, Area_sqft)
  

swm_results_dry<-read_csv("wailupe10_dry_summary.csv")

results_dry<- merge(subcatch, swm_results_dry, by = "subcatchment") %>% 
  mutate(runoff_normalized= 
           total_runoff_in/Area_sqft) %>% 
  mutate(Urbanization_level= 
           case_when(
             percent_imp <15 |percent_imp == 15 ~ "Natural (less than 15 % Impervious)",
             percent_imp >15 & percent_imp <45 ~ "Urbanized (Between 15 and 45 % Impervious)",
             percent_imp >44.9999 ~ "Very urbanized (More than 45 % Impervious)"
             )
           )


results_regression_dry<- lm(total_runoff_in ~Curve_Number + Slope + percent_imp + Area_sqft, data = results_dry)

regress_dry_norm<- lm(runoff_normalized ~Curve_Number + Slope + percent_imp + Area_sqft, data = results_dry)

runoff_imp_graph_dry<- results_dry %>% 
  ggplot(aes(x=percent_imp, y=total_runoff_in))+
  geom_point(aes(color=Urbanization_level))+
  labs(x= "Percent Impervious of Subcatchment", y= "Total Simulated Runoff (inches)")+
  scale_y_continuous(limits= c(0,7), breaks= seq(0,7, by= 1),expand= c(0,0.08))+
  scale_x_continuous(limits= c(0,80), breaks= seq(0,80, by= 10),expand= c(0,0))+
  scale_color_manual(name= "Urbanization Level", values= c("darkgreen", "darkseagreen", "darkgoldenrod1"))+
  theme_classic()


runoff_imp_graph_dry


## save runoff vs. impervious graph
ggsave("runoff_imp_dry.pdf", width = 8, height =4)
ggsave("runoff_imp_dry.png", width = 8, height =4)

library(stargazer)

regress_table_dry<- stargazer(results_regression_dry, type ="html", digits= 2, 
                          dep.var.labels = "Total Runoff (Inches)", 
                       covariate.labels = c("Curve Number", "Slope", "Percent Impervious", "Area (sqft)", "Y-Intercept"), 
                       omit.stat = c("rsq"))

regress_table_dry



```

```{r}
#wetsummary

swm_results_wet<-read_csv("Wailupe10_wet_summary.csv")

results_wet<- merge(subcatch, swm_results_wet, by = "subcatchment") %>% 
  mutate(runoff_normalized= 
           total_runoff_in/Area_sqft) %>% 
  mutate(Urbanization_level= 
           case_when(
             percent_imp <15 |percent_imp == 15 ~ "Natural (less than 15 % Impervious)",
             percent_imp >15 & percent_imp <45 ~ "Urbanized (Between 15 and 45 % Impervious)",
             percent_imp >44.9999 ~ "Very urbanized (More than 45 % Impervious)"
             )
           )


results_regression_wet<- lm(total_runoff_in ~Curve_Number + Slope + percent_imp + Area_sqft, data = results_wet)

runoff_imp_graph_wet<- results_wet %>% 
  ggplot(aes(x=percent_imp, y=total_runoff_in))+
  geom_point(aes(color=Urbanization_level))+
  labs(x= "Percent Impervious of Subcatchment", y= "Total Simulated Runoff (inches)")+
  scale_y_continuous(limits= c(0,3), breaks= seq(0,2.5, by= 0.5),expand= c(0,0.08))+
  scale_x_continuous(limits= c(0,80), breaks= seq(0,80, by= 10),expand= c(0,0))+
  scale_color_manual(name= "Urbanization Level", values= c("darkgreen", "darkseagreen", "darkgoldenrod1"))+
  theme_classic()

runoff_norm_wet<- results_wet %>% 
  ggplot(aes(x=percent_imp, y=runoff_normalized))+
  geom_point(aes(color=Urbanization_level))+
  labs(x= "Percent Impervious of Subcatchment", y= "Total Simulated Runoff Normalized by Area (inches/sqft)")+
  scale_y_continuous(expand= c(0,0))+
  scale_x_continuous(limits= c(0,80), breaks= seq(0,80, by= 10),expand= c(0,0))+
  scale_color_manual(name= "Urbanization Level", values= c("darkgreen", "darkseagreen", "darkgoldenrod1"))+
  theme_classic()

runoff_norm_wet
runoff_imp_graph_wet

##save runoff vs. impervious graph
ggsave("runoff_imp_wet.pdf", width = 8, height =4)
ggsave("runoff_imp_wet.png", width = 8, height =4)


regress_table_wet<- stargazer(results_regression_wet, type ="html", digits= 2, 
                          dep.var.labels = "Total Runoff (Inches)", 
                       covariate.labels = c("Curve Number", "Slope", "Percent Impervious", "Area (sqft)", "Y-Intercept"), 
                       omit.stat = c("rsq"))

regress_table_wet


```


```{r}
#graph observed vs simulated

observed<- read_csv("c35_observed.csv")
simulated <- read_csv("C35_simulated_adj_cn25.csv")

discharge<- merge(observed, simulated, by = "time_step")

summary(discharge)


dischargettest<- t.test(discharge$discharge_obs_cfs, discharge$simulated_flow_cfs)

regress<- lm(discharge_obs_cfs ~ simulated_flow_cfs, data = discharge)

regress

sim<- discharge$simulated_flow_cfs
obs<- discharge$discharge_obs_cfs

library(hydroGOF)

sutcliffe<- NSE(sim, obs, na.rm=TRUE, FUN=NULL, epsilon=c("Pushpalatha2012"))

sutcliffe

write.csv(discharge,"C:\\Users\\eleon\\Documents\\Bren\\Malama Maunalua\\discharge_obv_sim1.csv", row.names = FALSE)

graph<- ggplot(discharge, aes(x=discharge_obs_cfs, simulated_flow_cfs))+
  geom_point()

graph

  
calibrate_graph<- discharge %>% 
  ggplot()+
  geom_line(aes(x=time_step, y=discharge_obs_cfs), color="darkseagreen")+
  geom_line(aes(x=time_step, y=simulated_flow_cfs), color= "darkgoldenrod1")+
  theme_classic()+
  labs(x="Time (hours)", y="Discharge (cfs)")+
  scale_y_continuous(limits= c(0,275), breaks= seq(0,250, by= 25),expand= c(0,0))+
  scale_x_continuous(limits= c(0,22), breaks= seq(0,22, by= 2),expand= c(0,0))+
  annotate("text", label= "Observed", x=19.5, y=65, size=3.5)+
  annotate("text", label= "Simulated", x=19.5, y=25, size=3.5)
 

calibrate_graph  

##save discharge graphs from the 2010 "dry" storm
ggsave("discharge10.pdf", width = 8, height =4)
ggsave("dischage10.png", width = 8, height =4)

results_table<- results_wet %>% 
  group_by(Urbanization_level) %>% 
  summarize(
    number_of_subcatch=length(subcatchment),
    runoff_coefficient=round(mean(runoff_coeff),2), 
    total_runoff_inches=round(mean(total_runoff_in),2), 
    impervious_runoff_inches=round(mean(imperv_runoff_in),2), 
    pervious_runoff_inches=round(mean(perv_runoff_in), 2),
    total_infiltration_inches= round(mean(total_infil_in),2),
    peak_runoff_cubicfs=round(mean(peak_runoff_cfs),2)
    
  )
  
results_table
library(kableExtra)

table_pretty<-results_table %>% 
              kable(col.names=c("Urbanization Level","Number of Subcatchments", "Runoff Coefficient", "Total Runoff (in)", "Impervious Runoff (in)", "Pervious Runoff (in)","Total Infiltration (in)", "Peak Runoff (cfs)")) %>% 
  kable_styling(bootstrap_options = "striped")

table_pretty
               

```

```{r}
observed09<- read_csv("c35_observed_09.csv")
simulated09 <- read_csv("C35_simulated09.csv") 

discharge09<- merge(observed09, simulated09, by = "time_step")

summary(discharge09)

dischargettest09<- t.test(discharge09$discharge_obs_cfs, discharge09$simulated_flow_cfs)

regress09<- lm(discharge_obs_cfs ~ simulated_flow_cfs, data = discharge09)

regress09

sim09<- discharge09$simulated_flow_cfs
obs09<- discharge09$discharge_obs_cfs


sutcliffe09<- NSE(sim09, obs09, na.rm=TRUE, FUN=NULL, epsilon=c("Pushpalatha2012"))

sutcliffe09

#write.csv(discharge,"C:\\Users\\eleon\\Documents\\Bren\\Malama Maunalua\\discharge_obv_sim1.csv", row.names = FALSE)

graph09<- ggplot(discharge09, aes(x=discharge_obs_cfs, simulated_flow_cfs))+
  geom_point()

graph
  
calibrate_graph09<- discharge09 %>% 
  ggplot()+
  geom_line(aes(x=time_step, y=discharge_obs_cfs), color="darkseagreen")+
  geom_line(aes(x=time_step, y=simulated_flow_cfs), color= "darkgoldenrod1")+
  theme_classic()+
  labs(x="Time (hours)", y="Discharge (cfs)")+
  scale_y_continuous(limits= c(0,275), breaks= seq(0,250, by= 25),expand= c(0,0))+
  scale_x_continuous(limits= c(0,12), breaks= seq(0,12, by= 2),expand= c(0,0))+
  annotate("text", label= "Observed", x=8, y=150, size=3.5)+
  annotate("text", label= "Simulated", x=8, y=77, size=3.5)


calibrate_graph09  

##save discharge graphs from the 2009 "wet" storm
ggsave("discharge09.pdf", width = 8, height =4)
ggsave("dischage09.png", width = 8, height =4)
```

