---
title: "Soil Curve Number Adjustments"
author: "Eleonore Durand"
date: "May 13, 2020"
output:
  pdf_document: default
  html_document: default
subtitle: This is code to adjust the soil curve numbers for each subcatchment in Wailupe
  using weighted means.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Code Setup
```{r, warning = FALSE, message = FALSE}
library(tidyverse) #loading in the packages
```

## Weighted means for curve numbers
```{r, message = FALSE}
#Load data for curve numbers from final curve numbers code
ind_cn_all<- read_csv("subcatch_2_12_cn.csv") %>% 
  filter (curve_numbers_csv_CN != "NA") 

all_cn_weighted<- ind_cn_all %>% 
  group_by(OBJECTID_1) %>% #grouping by subcatchment and then doing a weighted mean
  summarize(mean_cn= weighted.mean(curve_numbers_csv_CN, PERCENTAGE))

slopes_ind<- read_csv("subcatch_2_12_slope.csv")

slope_weighted<- slopes_ind %>% 
  group_by(OBJECTID_1) %>% #grouping by subcatchment and then doing a weighted mean
  summarize(mean_slope=weighted.mean(Slope, PERCENTAGE))

write.csv(all_cn_weighted, file = "subcatch_2_12_cn_weighted.csv")
  
write.csv(slope_weighted, file = "subcatch_2_12_slope_weighted.csv")


```

